const ShopActionTypes = {
    FETCH_COLLECTIONS_START: '@@shop/FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: '@@shop/FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: '@@shop/FETCH_COLLECTIONS_FAILURE'
}

export default ShopActionTypes